name: Automatic approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      name: Automatic approval
      uses: pullreminders/label-when-approved-action@master
      env:
          APPROVAL: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "PR is approved"
